[package]
name = "oxy_render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
oxy_core.workspace = true
eframe.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
glam.workspace = true
image.workspace = true
bytemuck.workspace = true

[dev-dependencies]
serde_json.workspace = true
